// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfrqqdyxzgeodbzovggo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmcnFxZHl4emdlb2Riem92Z2dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNTA3NjMsImV4cCI6MjA4NTkyNjc2M30.rendr7cijlAM12KrSfmiW9_6u3H43ppOiNb8Z2kPLQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});